# https://taskfile.dev

version: '3'

silent: true

tasks:
  install:
    desc: "Install VitePress dependencies using pnpm"
    silent: true
    cmds:
      - pnpm install

  dev:
    desc: "Run local dev server to preview the docs"
    silent: true
    cmds:
      - pnpm docs:dev

  build:
    desc: "Build the docs website"
    silent: true
    cmds:
      - pnpm docs:build

  preview:
    desc: "Preview the built docs website"
    silent: true
    cmds:
      - pnpm docs:preview